DECLARE

  V_ID_USER NUMBER(3);
  V_DT_LOG  DATE;
  V_QTD     integer;

BEGIN

  FOR I IN (SELECT U.ID_USUARIO, MAX(L.DT_LOGIN) AS DT_LOGIN
              FROM S01USUARIO U, LOG_USER L
             WHERE U.ID_USUARIO = L.ID_USUARIO
               AND U.STATUS = 'A'
             GROUP BY U.ID_USUARIO) LOOP
  
    SELECT ROUND(SYSDATE - I.DT_LOGIN) INTO V_QTD FROM DUAL;
  
    IF V_QTD > 60 THEN
    
      UPDATE S01USUARIO
         SET STATUS = 'I'
       WHERE ID_USUARIO = I.ID_USUARIO
         AND STATUS = 'A';
    
      DBMS_OUTPUT.PUT_LINE('USUARIO INATIVADO: ' || I.ID_USUARIO);
    
    END IF;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('NAO FOI ENCONTRADO USUARIO PARA SER INATIVADO');
END;
